"""Reusable model mixins — the PATTERNS every table builds on.

This file establishes conventions only (UUID PKs, timestamps); it does NOT define
the domain tables (companies, reports, document_chunks, ...). Those are added in
their respective phases and should compose these mixins, e.g.:

    class Company(UUIDMixin, TimestampMixin, Base):
        __tablename__ = "companies"
        name: Mapped[str] = mapped_column(Text, nullable=False)

Conventions (see docs/02_DATABASE_DESIGN.md §3):
  * Primary keys are UUIDs generated server-side (`gen_random_uuid()` via pgcrypto).
  * Timestamps are timezone-aware (`timestamptz`), defaulted in the DB.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column


class UUIDMixin:
    """Adds a non-guessable UUID primary key generated by PostgreSQL."""

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """Adds DB-managed created_at / updated_at (timestamptz, UTC)."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
