"""Canonical hedging phrases for rule-based uncertainty detection."""

HEDGING_PHRASES = [
    "may",
    "might",
    "could",
    "potentially",
    "uncertain",
    "subject to",
    "depends on",
    "possible",
    "possibly",
    "estimate",
    "estimated",
    "approximate",
    "approximately",
    "unpredictable",
    "variability",
    "volatile",
    "volatility",
    "forecast",
    "speculative",
    "assumes",
    "assuming",
    "potential risks",
    "some degree",
    "not guarantee",
    "contingent upon",
]
