"""Canonical negative phrases for rule-based sentiment scoring."""

NEGATIVE_PHRASES = [
    "declining demand",
    "headwinds",
    "pressure",
    "weakness",
    "contraction",
    "operational challenges",
    "margin pressure",
    "supply chain disruption",
    "revenue decline",
    "underperformance",
    "increased competition",
    "reduced guidance",
    "macroeconomic uncertainty",
    "softer market",
    "cost inflation",
    "regulatory hurdles",
    "negative impact",
    "impairment charge",
    "capacity constraints",
    "lower volume",
    "sluggish growth",
    "decrease in net",
    "higher expenses",
    "unfavorable impact",
    "credit deterioration",
]
