"""Canonical positive phrases for rule-based sentiment scoring."""

POSITIVE_PHRASES = [
    "strong growth",
    "record performance",
    "exceeded expectations",
    "robust demand",
    "accelerating adoption",
    "increased profitability",
    "revenue expansion",
    "market leadership",
    "favorable trends",
    "improved efficiency",
    "optimistic outlook",
    "successful integration",
    "positive momentum",
    "outstanding results",
    "double-digit growth",
    "solid execution",
    "strong cash flow",
    "margin expansion",
    "operational excellence",
    "strategic success",
    "historic high",
    "healthy demand",
    "exceptional performance",
    "clear upside",
    "highly productive",
]
